import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import { Link, Route, Switch, useLocation } from 'wouter';
import { ArrowRight, ChevronRight, Copy, Facebook, Instagram, Menu, Moon, Search, Share2, Sun, X, Youtube } from 'lucide-react';
import { articles, authors, categories, categoryArticles, formatDate, getArticle, getAuthor, getCategory, site, tickerItems, type Article } from './data';
import Analytics from './Analytics';

const banner = '/manus-storage/today-khabar-website-banner_d56dcb81.png';

type Lang = 'ne' | 'en';
const LangContext = createContext<{ lang: Lang; setLang: (lang: Lang) => void; dark: boolean; setDark: (dark: boolean) => void }>({ lang: 'ne', setLang: () => {}, dark: false, setDark: () => {} });
const useSitePrefs = () => useContext(LangContext);
const bi = (ne: string, en: string, lang: Lang) => lang === 'ne' ? ne : en;

function Logo({ compact = false }: { compact?: boolean }) {
  return <Link href="/" className="brand" aria-label="Today Khabar home">
    <span className="brand-mark"><span>T</span><span>K</span></span>
    <span className="brand-copy"><strong>{compact ? 'TODAY KHABAR' : 'TODAY KHABAR'}</strong><small>{site.tagline}</small></span>
  </Link>;
}

function Header() {
  const [open, setOpen] = useState(false);
  const { lang, setLang, dark, setDark } = useSitePrefs();
  const [location] = useLocation();
  return <>
    <div className="topline"><div className="container top-inner"><span>{bi('शुक्रबार, २ असोज २०८३', 'Friday, 18 September 2026', lang)}</span><span className="top-note">{bi('प्रकाशनपूर्व डेमो संस्करण · तथ्य प्रमाणीकरणपछि मात्र समाचार प्रकाशन', 'Preview edition · Stories are published only after verification', lang)}</span><div className="top-links"><Link href="/about">{bi('हाम्रो बारेमा', 'About', lang)}</Link><Link href="/contact">{bi('सम्पर्क', 'Contact', lang)}</Link><button className="lang-toggle" onClick={() => setLang(lang === 'ne' ? 'en' : 'ne')} aria-label="Change language">{lang === 'ne' ? 'EN' : 'नेपाली'}</button><button className="theme-toggle" onClick={() => setDark(!dark)} aria-label={dark ? 'Switch to light mode' : 'Switch to dark mode'}>{dark ? <Sun size={14} /> : <Moon size={14} />}</button></div></div></div>
    <header className="site-header"><div className="container header-inner"><Logo /><div className="header-actions"><Link href="/search" className="icon-button" aria-label="Search"><Search size={20} /></Link><button className="menu-button" aria-label="Open menu" onClick={() => setOpen(!open)}><Menu size={21} /></button></div></div>
      <nav className={`nav-wrap ${open ? 'open' : ''}`} aria-label="Primary navigation"><div className="container nav-inner"><Link className={location === '/' ? 'active' : ''} href="/">{bi('गृहपृष्ठ', 'Home', lang)}</Link><Link className={location === '/latest' ? 'active' : ''} href="/latest">{bi('ताजा', 'Latest', lang)}</Link>{categories.slice(0, 8).map(c => <Link key={c.slug} className={location === `/${c.slug}` ? 'active' : ''} href={`/${c.slug}`}>{lang === 'ne' ? c.name : c.english}</Link>)}<Link href="/opinion">{bi('विचार', 'Opinion', lang)}</Link><Link className="search-link" href="/search"><Search size={16} /> {bi('खोज्नुहोस्', 'Search', lang)}</Link><span className="social-nav"><a href={site.social.facebook} target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook size={15} /></a><a href={site.social.instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={15} /></a></span></div></nav>
    </header>
    <div className="trend-ticker" role="status"><div className="container trend-ticker-inner"><span className="ticker-label">{bi('ट्रेन्डिङ', 'TRENDING', lang)}</span><div className="ticker-track">{articles.slice(0, 3).map((article, index) => <Link key={article.id} href={`/news/${article.slug}`}><b>0{index + 1}</b> {article.title}</Link>)}</div><ChevronRight size={16} /></div></div>
  </>;
}

function Footer() { return <footer className="footer"><div className="container footer-grid"><div><Logo /><p className="footer-intro">जिम्मेवार पत्रकारिता, स्पष्ट सन्दर्भ र पाठकप्रतिको जवाफदेहिता।</p><div className="socials"><a aria-label="Facebook" href={site.social.facebook || '#'}><Facebook size={17} /></a><a aria-label="YouTube" href={site.social.youtube || '#'}><Youtube size={17} /></a><a aria-label="Instagram" href={site.social.instagram || '#'}><Instagram size={17} /></a><a aria-label="X" href={site.social.x || '#'}><X size={16} /></a></div></div><div><h4>वर्गहरू</h4>{categories.slice(0, 6).map(c => <Link key={c.slug} href={`/${c.slug}`}>{c.name}</Link>)}</div><div><h4>पारदर्शिता</h4><Link href="/about">हाम्रो बारेमा</Link><Link href="/editorial-policy">सम्पादकीय नीति</Link><Link href="/corrections">सुधार नीति</Link><Link href="/authors">लेखकहरू</Link></div><div><h4>कानुनी</h4><Link href="/privacy-policy">गोपनीयता नीति</Link><Link href="/terms">नियम तथा सर्त</Link><Link href="/contact">सम्पर्क</Link><div className="ad-mini">Advertisement<br /><span>वास्तविक विज्ञापन कन्फिगरेसन पछि जोडिनेछ</span></div></div></div><div className="container footer-bottom"><span>© २०८३ Today Khabar. सर्वाधिकार सुरक्षित।</span><span>समाचार सामग्रीको स्रोत र मिति स्पष्ट राखिन्छ।</span></div></footer> }

function AdSlot({ label = 'Advertisement' }: { label?: string }) { return <div className="ad-slot"><span>{label}</span><small>विज्ञापन स्थान · प्रकाशक ID कन्फिगरेसन बाँकी</small></div> }

function SectionHeading({ eyebrow, title, href }: { eyebrow?: string; title: string; href?: string }) { return <div className="section-heading"><div><span className="eyebrow">{eyebrow ?? 'Today Khabar'}</span><h2>{title}</h2></div>{href && <Link href={href} className="more-link">सबै हेर्नुहोस् <ArrowRight size={16} /></Link>}</div> }

function NewsCard({ article, featured = false }: { article: Article; featured?: boolean }) { return <Link href={`/news/${article.slug}`} className={`news-card ${featured ? 'featured-card' : ''}`}><div className="card-image"><img src={article.image} alt={article.imageAlt} loading="lazy" /><span className="card-category">{getCategory(article.category)?.name}</span></div><div className="card-content"><div className="card-meta"><span>{formatDate(article.publishedAt)}</span><span>·</span><span>{article.readingTime}</span></div><h3>{article.title}</h3><p>{article.excerpt}</p></div></Link> }

function LoadMoreFeed({ items, initialCount = 2 }: { items: Article[]; initialCount?: number }) { const [visible, setVisible] = useState(initialCount); const shown = items.slice(0, visible); return <><div className="latest-list">{shown.map(article => <NewsCard key={article.id} article={article} />)}</div>{visible < items.length && <button className="load-more" onClick={() => setVisible(current => Math.min(current + 2, items.length))}>Load more / थप समाचार <ArrowRight size={16} /></button>}</> }

function Newsletter() { const [done, setDone] = useState(false); return <section className="newsletter"><div><span className="eyebrow">THE MORNING BRIEF</span><h2>दिनको महत्वपूर्ण कुरा,<br /><em>तपाईंको इनबक्समा।</em></h2><p>प्रमाणित र सन्दर्भयुक्त समाचारको साप्ताहिक संक्षेप।</p></div>{done ? <div className="success-note">धन्यवाद। तपाईंको रुचि सुरक्षित गरियो।</div> : <form onSubmit={(e) => { e.preventDefault(); setDone(true); }}><input aria-label="Email address" type="email" required placeholder="तपाईंको इमेल" /><button type="submit">सदस्यता लिनुहोस् <ArrowRight size={17} /></button><small>स्पाम छैन। जुनसुकै बेला सदस्यता रद्द गर्न सकिन्छ।</small></form>}</section> }

function Home() { const featured = articles[0]; return <><Header /><main><section className="hero container"><div className="hero-copy"><span className="eyebrow">आजको मुख्य कुरा · EDITORIAL PREVIEW</span><h1>समाचारमा <em>विश्वास</em>,<br />सन्दर्भमा स्पष्टता।</h1><p>{site.description}</p><div className="hero-buttons"><Link className="primary-button" href={`/news/${featured.slug}`}>नमुना सामग्री पढ्नुहोस् <ArrowRight size={17} /></Link><Link className="quiet-button" href="/about">हाम्रो दृष्टिकोण</Link></div></div><div className="hero-art"><img src={banner} alt="Today Khabar Kathmandu and Himalaya banner" /></div></section><div className="breaking"><div className="container breaking-inner"><span className="breaking-label">BREAKING</span><p>यो डेमो संस्करण हो — वास्तविक समाचार प्रकाशनअघि स्रोत र तथ्य प्रमाणीकरण गरिनेछ।</p><ChevronRight size={17} /></div></div><section className="container section-pad"><SectionHeading eyebrow="CURATED FOR YOU" title="आजको सम्पादकीय डेस्क" href="/latest" /><div className="lead-grid"><NewsCard article={featured} featured /><div className="side-stories">{articles.slice(1, 3).map(a => <NewsCard key={a.id} article={a} />)}</div><aside className="editor-note"><span className="eyebrow">EDITOR'S NOTE</span><h3>पहिले स्रोत,<br />त्यसपछि कथा।</h3><p>Today Khabar को वाचा सरल छ: पाठकलाई के थाहा छ, के थाहा छैन र कुन स्रोतमा आधारित छ — सबै कुरा स्पष्ट बताउने।</p><Link href="/editorial-policy">सम्पादकीय नीति <ArrowRight size={15} /></Link></aside></div></section><section className="tint-section"><div className="container section-pad"><SectionHeading eyebrow="EXPLORE TOPICS" title="वर्गअनुसार पढ्नुहोस्" /> <div className="category-grid">{categories.slice(0, 8).map((c, i) => <Link key={c.slug} href={`/${c.slug}`} className="category-tile"><span>0{i + 1}</span><strong>{c.name}</strong><small>{c.english}</small><ArrowRight size={17} /></Link>)}</div></div></section><section className="container section-pad"><div className="content-with-sidebar"><div><SectionHeading eyebrow="LATEST" title="ताजा अपडेट" href="/latest" /><LoadMoreFeed items={articles} /></div><aside><AdSlot /><div className="trend-box"><span className="eyebrow">TRENDING</span><h3>पाठकहरूले खोजिरहेका विषय</h3>{['स्रोत प्रमाणीकरण', 'डिजिटल साक्षरता', 'सम्पादकीय पारदर्शिता', 'नेपाल र विश्व'].map((t, i) => <Link key={t} href="/search" className="trend-row"><b>0{i + 1}</b><span>{t}</span><ArrowRight size={15} /></Link>)}</div></aside></div></section><section className="container section-pad"><Newsletter /></section></main><Footer /></> }

function ListingPage({ slug, title }: { slug?: string; title: string }) { const list = slug ? categoryArticles(slug) : articles; const category = slug ? getCategory(slug) : undefined; return <><Header /><main className="container page-shell"><div className="breadcrumbs"><Link href="/">गृहपृष्ठ</Link><ChevronRight size={14} />{title}</div><div className="page-title"><span className="eyebrow">{category?.english ?? 'LATEST NEWS'}</span><h1>{title}</h1><p>{category?.blurb ?? 'प्रकाशन मिति र स्रोतसहित क्रमबद्ध रूपमा राखिएका सामग्री।'}</p></div><AdSlot /><div className="listing-layout"><div className="listing-grid">{list.length ? list.map(a => <NewsCard key={a.id} article={a} />) : <div className="empty-state"><h3>यस वर्गमा सामग्री तयार हुँदैछ।</h3><p>प्रकाशनपूर्व डेस्कले प्रमाणित सामग्री तयार गरेपछि यहाँ देखिनेछ।</p></div>}</div><aside><div className="side-sticky"><SectionHeading eyebrow="MOST READ" title="लोकप्रिय" />{articles.slice(0, 3).map((a, i) => <Link className="mini-story" key={a.id} href={`/news/${a.slug}`}><b>0{i + 1}</b><span>{a.title}</span></Link>)}</div></aside></div></main><Footer /></> }

function SearchPage() { const [q, setQ] = useState(''); const results = useMemo(() => { const term = q.trim().toLowerCase(); return term ? articles.filter(a => [a.title, a.excerpt, a.category, a.tags.join(' '), getAuthor(a.authorId).name].join(' ').toLowerCase().includes(term)) : []; }, [q]); return <><Header /><main className="container page-shell"><div className="page-title"><span className="eyebrow">SEARCH</span><h1>समाचार खोज्नुहोस्</h1><p>शीर्षक, वर्ग, ट्याग वा लेखकका आधारमा खोजी गर्नुहोस्।</p></div><div className="search-form"><Search size={21} /><input autoFocus value={q} onChange={e => setQ(e.target.value)} placeholder="जस्तै: प्रविधि, शिक्षा, सम्पादकीय..." /></div>{q && <p className="result-count">“{q}” का लागि {results.length} परिणाम</p>}<div className="listing-grid search-results">{results.map(a => <NewsCard key={a.id} article={a} />)}{q && results.length === 0 && <div className="empty-state"><h3>परिणाम भेटिएन।</h3><p>फरक शब्द प्रयोग गरेर पुनः प्रयास गर्नुहोस्।</p></div>}</div></main><Footer /></> }

function ShareButtons({ article }: { article: Article }) { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard?.writeText(window.location.href); setCopied(true); setTimeout(() => setCopied(false), 1600); }; return <div className="share-row"><span><Share2 size={16} /> साझा गर्नुहोस् / Share</span><a aria-label="Share on Facebook" title="Facebook" href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}`} target="_blank" rel="noreferrer"><Facebook size={17} /></a><a aria-label="Share on Twitter" title="Twitter" href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(window.location.href)}&text=${encodeURIComponent(article.title)}`} target="_blank" rel="noreferrer"><X size={17} /></a><a aria-label="Share on WhatsApp" title="WhatsApp" href={`https://wa.me/?text=${encodeURIComponent(article.title + ' ' + window.location.href)}`} target="_blank" rel="noreferrer">WA</a><button onClick={copy} aria-label="Copy link">{copied ? '✓' : <Copy size={16} />}</button></div> }

function ArticlePage({ slug }: { slug: string }) { const article = getArticle(slug); if (!article) return <NotFound />; const author = getAuthor(article.authorId); const category = getCategory(article.category); return <><Header /><main className="container article-shell"><div className="breadcrumbs"><Link href="/">गृहपृष्ठ</Link><ChevronRight size={14} /><Link href={`/${article.category}`}>{category?.name}</Link><ChevronRight size={14} />समाचार</div><article><div className="article-kicker"><span>{category?.name}</span><span>प्रकाशनपूर्व नमुना</span></div><h1>{article.title}</h1><p className="article-dek">{article.excerpt}</p><div className="article-byline"><div className="avatar">{author.name.slice(0, 1)}</div><div><strong>{author.name}</strong><span>{author.role} · {formatDate(article.publishedAt)} · {article.readingTime}</span></div></div><ShareButtons article={article} /><div className="article-image"><img src={article.image} alt={article.imageAlt} /></div><div className="article-layout"><div className="article-body">{article.body.map(p => <p key={p}>{p}</p>)}<div className="notice-box"><strong>पारदर्शिता सूचना</strong><p>यो सामग्री वेबसाइटको संरचना देखाउन राखिएको प्रकाशनपूर्व नमुना हो। यसलाई वास्तविक समाचार वा प्रमाणित घटनाको रिपोर्टका रूपमा नलिनुहोस्।</p></div><div className="article-tags">{article.tags.map(tag => <span key={tag}>#{tag}</span>)}</div><div className="source-line"><strong>स्रोत:</strong> {article.source}</div></div><aside><AdSlot /><div className="author-box"><span className="eyebrow">ABOUT THE AUTHOR</span><h3>{author.name}</h3><p>{author.bio}</p><Link href="/authors">सबै लेखकहरू <ArrowRight size={15} /></Link></div></aside></div></article><section className="related"><SectionHeading eyebrow="KEEP READING" title="सम्बन्धित सामग्री" /> <div className="related-grid">{articles.filter(a => a.id !== article.id).slice(0, 3).map(a => <NewsCard key={a.id} article={a} />)}</div></section></main><Footer /></> }

const legalContent: Record<string, { title: string; intro: string; sections: [string, string][] }> = { '/about': { title: 'हाम्रो बारेमा', intro: 'Today Khabar नेपाल र नेपाली भाषी पाठकका लागि तयार हुँदै गरेको जिम्मेवार डिजिटल समाचार प्लेटफर्म हो।', sections: [['हाम्रो उद्देश्य', 'स्रोत, सन्दर्भ र स्पष्ट भाषामार्फत पाठकलाई उपयोगी सूचना उपलब्ध गराउनु हाम्रो उद्देश्य हो।'], ['प्रकाशन स्थिति', 'यो पहिलो संस्करण प्रकाशनपूर्व संरचना र नमुना सामग्रीसहित तयार गरिएको हो। वास्तविक समाचार प्रकाशनअघि प्रत्येक सामग्रीको स्रोत, मिति र तथ्य प्रमाणीकरण गरिनेछ।']] }, '/contact': { title: 'सम्पर्क', intro: 'समाचार सुझाव, सुधार अनुरोध वा साझेदारीसम्बन्धी कुराकानीका लागि हामीलाई लेख्नुहोस्।', sections: [['सम्पादकीय डेस्क', 'Email: hello@todaykhabar.example'], ['सुधार अनुरोध', 'कुनै प्रकाशित सामग्रीमा तथ्यगत त्रुटि भेटिएमा शीर्षक, URL र सुधारको आधारसहित सम्पर्क गर्नुहोस्।']] }, '/privacy-policy': { title: 'गोपनीयता नीति', intro: 'यो नमुना नीतिले वेबसाइटले आगन्तुकको जानकारी कसरी व्यवहार गर्नेछ भन्ने आधारभूत ढाँचा बताउँछ।', sections: [['सङ्कलन हुने जानकारी', 'सम्पर्क वा न्यूजलेटर फारममा तपाईंले स्वेच्छाले दिएको जानकारी मात्र प्रयोग गरिनेछ। विश्लेषण सेवा जोडिएमा आवश्यक कन्फिगरेसन र सूचना छुट्टै प्रकाशित गरिनेछ।'], ['कुकी र तेस्रो पक्ष', 'वास्तविक विज्ञापन वा विश्लेषण सेवा सक्रिय गर्नुअघि सम्बन्धित कुकी र सहमति व्यवस्थापन थपिनेछ।']] }, '/terms': { title: 'नियम तथा सर्त', intro: 'वेबसाइट प्रयोग गर्दा जिम्मेवार र कानुनी प्रयोगको अपेक्षा गरिन्छ।', sections: [['सामग्री प्रयोग', 'सामग्रीलाई स्रोत र लिंकसहित उद्धृत गर्न सकिन्छ। सम्पूर्ण सामग्री जस्ताको तस्तै पुनःप्रकाशन गर्नुअघि अनुमति आवश्यक पर्न सक्छ।'], ['अस्वीकरण', 'यो वेबसाइटले समाचारको शुद्धता र समयसापेक्षताका लागि उचित सम्पादकीय प्रक्रिया अपनाउनेछ, तर कुनै बाह्य नतिजा वा सेवा उपलब्धताको ग्यारेन्टी गर्दैन।']] }, '/editorial-policy': { title: 'सम्पादकीय नीति', intro: 'विश्वसनीयता, पारदर्शिता र पाठकप्रतिको जवाफदेहिता हाम्रो सम्पादकीय आधार हो।', sections: [['स्रोत र प्रमाणीकरण', 'प्रकाशित सामग्रीमा प्राथमिक वा विश्वसनीय स्रोतको आधार, प्रकाशन मिति र लेखक विवरण स्पष्ट राखिनेछ। अपुष्ट दाबीलाई तथ्यका रूपमा प्रस्तुत गरिने छैन।'], ['विचार र समाचार', 'समाचार, विश्लेषण र विचारलाई स्पष्ट लेबलद्वारा छुट्याइनेछ। हितसम्बन्ध र सम्भावित द्वन्द्व भएमा पारदर्शी रूपमा उल्लेख गरिनेछ।']] }, '/corrections': { title: 'सुधार नीति', intro: 'गल्ती लुकाउनु होइन, पहिचान गरेर स्पष्ट रूपमा सुधार गर्नु हाम्रो प्रतिबद्धता हो।', sections: [['सुधार प्रक्रिया', 'तथ्यगत त्रुटि पुष्टि भएमा सामग्रीमा सुधार सूचना र अद्यावधिक समय राखिनेछ। महत्त्वपूर्ण परिवर्तनको कारण र प्रकृति स्पष्ट गरिनेछ।'], ['सम्पर्क', 'सुधार अनुरोधका लागि सामग्रीको URL, त्रुटिको विवरण र प्रमाण hello@todaykhabar.example मा पठाउनुहोस्।']] } };

function LegalPage({ path }: { path: string }) { const page = legalContent[path] ?? legalContent['/about']; return <><Header /><main className="container page-shell legal-page"><div className="breadcrumbs"><Link href="/">गृहपृष्ठ</Link><ChevronRight size={14} />{page.title}</div><div className="page-title"><span className="eyebrow">TODAY KHABAR</span><h1>{page.title}</h1><p>{page.intro}</p></div><div className="legal-body">{page.sections.map(([h, p]) => <section key={h}><h2>{h}</h2><p>{p}</p></section>)}</div></main><Footer /></> }

function AuthorsPage() { return <><Header /><main className="container page-shell"><div className="page-title"><span className="eyebrow">THE NEWSROOM</span><h1>लेखकहरू</h1><p>प्रकाशित सामग्रीमा लेखकको भूमिका, स्रोत र जिम्मेवारी स्पष्ट रूपमा देखाइनेछ।</p></div><div className="authors-grid">{authors.map(a => <div className="author-card" key={a.id}><div className="avatar large">{a.name.slice(0, 1)}</div><span className="eyebrow">{a.role}</span><h2>{a.name}</h2><p>{a.bio}</p></div>)}</div></main><Footer /></> }
function NotFound() { return <><Header /><main className="container page-shell not-found"><span className="eyebrow">404 · NOT FOUND</span><h1>यो पृष्ठ भेटिएन।</h1><p>लिंक जाँच गर्नुहोस् वा गृहपृष्ठबाट पुनः सुरु गर्नुहोस्।</p><Link className="primary-button" href="/">गृहपृष्ठमा फर्कनुहोस् <ArrowRight size={17} /></Link></main><Footer /></> }

function AppRouter() { return <Switch><Route path="/" component={Home} /><Route path="/latest">{() => <ListingPage title="ताजा समाचार" />}</Route>{categories.map(c => <Route key={c.slug} path={`/${c.slug}`}>{() => <ListingPage slug={c.slug} title={c.name} />}</Route>)}<Route path="/search" component={SearchPage} /><Route path="/authors" component={AuthorsPage} /><Route path="/news/:slug">{params => <ArticlePage slug={params.slug} />}</Route>{Object.keys(legalContent).map(path => <Route key={path} path={path}>{() => <LegalPage path={path} />}</Route>)}<Route path="/404" component={NotFound} /><Route component={NotFound} /></Switch> }

export default function App() {
  const [lang, setLang] = useState<Lang>(() => (localStorage.getItem('today-khabar-lang') as Lang) || 'en');
  const [dark, setDark] = useState(() => localStorage.getItem('today-khabar-theme') === 'dark');
  useEffect(() => { localStorage.setItem('today-khabar-lang', lang); }, [lang]);
  useEffect(() => { localStorage.setItem('today-khabar-theme', dark ? 'dark' : 'light'); }, [dark]);
  return <LangContext.Provider value={{ lang, setLang, dark, setDark }}><div className={dark ? 'dark-mode' : ''}><Analytics /><AppRouter /></div></LangContext.Provider>;
}
